### ISSUE TITLE
How to convert the nested JSON msg to ros msg ?

### ISSUE THREAD

**Issue by patel999jay** [uos/rospy_message_converter#59]
I am trying to convert my nested json string to ros msg, but could not able to do that ?
```bash
{
        "position": {
            "latitude": 44.62,
            "longitude": -63.66
        },
        "state": "HALIFAX",
        "positional_uncertainty": 0,
        "classification": [
            {
            "type": "scanning",
            "confidence": 0.77
            },
            {
            "type": "scanning",
            "confidence": 0.8
            },
            {
            "type": "scanning",
            "confidence": 0.3
            }
        ]
        }
```

But when i try to convert this as ros msg, I am having an error indicating that `AttributeError: 'str' object has no attribute 'items'
`
What i did is : 
1. Created a custom msg for this.
2. For `python` this is just the another dictionary.
3. so i use `json_message_converter.convert_json_to_ros_message(msg_type, dict_msg)`
4. then try to publish the data.

What could go wrong ? Could you please point me in the right direction ?

**Comment by mintar** [comment]
You didn't post your custom message, so I can't answer in detail. Also you didn't post the full traceback, so we don't know where the AttributeError happened (I guess it's in rospy's serialization function).

My suggestion would be to go the other way around (convert an instance of your custom message to json) so that you know what json dictionary is expected, like this:

```python
>>> import std_msgs.msg
>>> ros_message = std_msgs.msg.String(data="Hello, Robot")
>>> convert_ros_message_to_json(ros_message)
'{"data": "Hello, Robot"}'
```

**Comment by patel999jay** [comment]
Here is my custom msg.
```bash
#SimpleContact.msg
Position position
State state
PositionalUncertainty positional_uncertainty
Classification classification
`
```bash
#Position.msg
float64 latitude
float64 longitude
`
```bash
#State.msg
string state
`
```bash
#PositionalUncertainty.msg
float64 positional_uncertainty
`
```bash
#Classification.msg
string type
float64 confidence
`
Here is the full traceback:
```bash
Traceback (most recent call last):
  File "/home/jay/python_catkin/install/tutorials/lib/tutorials/publisher_node", line 11, in <module>
    load_entry_point('tutorials==0.0.0', 'console_scripts', 'publisher_node')()
  File "/home/jay/python_catkin/install/tutorials/lib/python3.8/site-packages/tutorials/publisher_node.py", line 70, in main
    rclpy.spin(minimal_publisher)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/__init__.py", line 191, in spin
    executor.spin_once()
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 711, in spin_once
    raise handler.exception()
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 426, in handler
    await call_coroutine(entity, arg)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 340, in _execute_timer
    await await_or_execute(tmr.callback)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 118, in await_or_execute
    return callback(*args)
  File "/home/jay/python_catkin/install/tutorials/lib/python3.8/site-packages/tutorials/publisher_node.py", line 54, in timer_callback
    json_data = convert_json_to_ros_message(msg_type, s1)
  File "/home/jay/python_catkin/install/ros2_message_converter/lib/python3.8/site-packages/ros2_message_converter/json_message_converter.py", line 17, in convert_json_to_ros_message
    return message_converter.convert_dictionary_to_ros_message(message_type, dictionary, strict_mode=strict_mode)
  File "/home/jay/python_catkin/install/ros2_message_converter/lib/python3.8/site-packages/ros2_message_converter/message_converter.py", line 118, in convert_dictionary_to_ros_message
    for field_name, field_value in dictionary.items():
AttributeError: 'str' object has no attribute 'items'
`

**Comment by mintar** [comment]
I think you're in the wrong repo. The code you're using is probably from here: https://github.com/mehmetkillioglu/ros2_message_converter

However, I will publish a much-improved version of this (based on #55) soon (within the next 2 weeks).

**Comment by patel999jay** [comment]
so you mean if i try to convert my entire json msg as `data`, will that convert it in `ros_msg` format ?

**Comment by mintar** [comment]
No.

**Comment by mintar** [comment]
Could you please open a message at the https://github.com/mehmetkillioglu/ros2_message_converter? This repo doesn't
support ROS2 yet (but it will in 2 weeks), and you're not using the code here, so I can't really help you.
